#
# this file gets executed by every shell you start
#

eval `/usr/local/bin/environ /bin/tcsh -i${?prompt} -e emacs:vi`


# Set the value of the PRINTER environmental variable to the name
# of your default printer.  For printer names, see the file
# /etc/qconfig on AIX systems or /etc/printcap on other systems).
# The default value, "InvalidPrinter", prevents the lp command from
# accidently submitting print jobs to the batch queue.

setenv PRINTER InvalidPrinter


if( ${?prompt} ) then
	# put aliases and other things down here
	alias ls ls -F
	alias mail /usr/ucb/Mail
	alias purge /bin/rm '*~'
	alias ll 'ls -l \!*'
endif

# 15 Apr 2014, for my own build:
#source /nfs/slac/g/exo_data4/users/alexis4/software/exoout/setup.csh
#source ~/alexis-exo/systemFiles/slac/setup_root_and_g4.csh 

# pre-3/2014, per EXO confluence:
# https://confluence.slac.stanford.edu/x/gwIkBQ
source /nfs/slac/g/exo/software/builds/current/setup.csh

# to add exo fitting, 14 MAr 2014:
setenv LD_LIBRARY_PATH $EXOLIB/fitting/lib:$LD_LIBRARY_PATH


# 12 Mar 2014, per EXO https://confluence.slac.stanford.edu/x/gwIkBQ
# was not using this as of 12 Mar 2014, since default python is 2.7

setenv PYTHONPATH ${ROOTSYS}/lib
if ($?LD_LIBRARY_PATH) then
   setenv LD_LIBRARY_PATH /opt/TWWfsw/python25/lib/python2.5/config:${LD_LIBRARY_PATH}
else
  setenv LD_LIBRARY_PATH /opt/TWWfsw/python25/lib/python2.5/config
endif



# AGS, pre-3/2014
#source ~/.aliases
#source ~/.environment_vars

# 02 Apr 2014
source /u/xo/alexis4/.aliases
source /u/xo/alexis4/.environment_vars

