#
# this file gets executed by every shell you start
#

eval `/usr/local/bin/environ /bin/tcsh -i${?prompt} -e emacs:vi`


# Set the value of the PRINTER environmental variable to the name
# of your default printer.  For printer names, see the file
# /etc/qconfig on AIX systems or /etc/printcap on other systems).
# The default value, "InvalidPrinter", prevents the lp command from
# accidently submitting print jobs to the batch queue.

setenv PRINTER InvalidPrinter


if( ${?prompt} ) then
	# put aliases and other things down here
	alias ls ls -F
	alias mail /usr/ucb/Mail
	alias purge /bin/rm '*~'
	alias ll 'ls -l \!*'
endif

# TRUNK -- 03 May 2014, for rhel6, per confluence:
# https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=163480421
source /nfs/slac/g/exo/software/hudson/builds-rhel6-64/trunk/setup.csh

# old but important versions:
#source /nfs/slac/g/exo/software/hudson/builds-rhel6-64/svn-id/8274/setup.csh
#source /nfs/slac/g/exo/software/hudson/builds-rhel6-64/svn-id/9773/setup.csh

# for particle id, salt geometry checks:
#source /nfs/slac/g/exo/software/hudson/builds-rhel6-64/svn-id/9842/setup.csh

# majoron analysis
#source /nfs/slac/g/exo/software/hudson/builds-rhel6-64/svn-id/9594/setup.csh

# 09 Jun 2014, for my own geant4:
#source /nfs/slac/g/exo_data4/users/alexis4/software/geant/geant4.9.3.p02/env.csh > /dev/null

# 09 May 2014, for my own build w rhel6
# for trunk (leave the "source ... hudson ... " line above alone!):
#
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/offline/build

# for n-cap bug fix:
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/offline_nCap_Cu63/build

# for vladimir tests 14 Jun 2014:
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/exoout_bug_fix

# for beta scale tests
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/offline_beta_scale/build

# javier
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/offline_javier/build

# michal tarka
#setenv EXOOUT /nfs/slac/g/exo_data4/users/alexis4/software/offline_tarka/build

# for my own builds:
#source $EXOOUT/setup.csh


# to add exo fitting, 14 MAr 2014:
#setenv LD_LIBRARY_PATH $EXOLIB/fitting/lib:$LD_LIBRARY_PATH

# aliases for sourcing different EXOAnalysis setup versions:
alias source_trunk 'source /nfs/slac/g/exo_data4/users/alexis4/software/exoout/setup.csh'
alias source_offline_veto_panels 'source /nfs/slac/g/exo_data4/users/alexis4/software/exoout_offline_veto_panels/setup.csh'
alias source_offline_veto_daq 'source /nfs/slac/g/exo_data4/users/alexis4/software/exoout_offline_veto_daq/setup.csh'

# some handy soft links, 14 May 2014
setenv PATH /nfs/slac/g/exo_data4/users/alexis4/software/bin:${PATH}

# AGS, pre-3/2014
#source ~/.aliases
#source ~/.environment_vars

# 02 Apr 2014
source /u/xo/alexis4/.aliases
source /u/xo/alexis4/.environment_vars

# use alternate .viminfo location 31 May 2014
alias vim 'vim -i /nfs/slac/g/exo_data4/users/alexis4/.viminfo'

alias myjobs 'bjobs | grep alexis ; echo "total:" ; bjobs | grep alexis | wc -l ; echo "running" ; bjobs | grep alexis | grep " RUN" | wc -l'


